Eureka
--------------------


Eureka is a REST (Representational State Transfer) based service that is primarily used in the AWS cloud for locating services for the purpose of load balancing and failover of middle-tier servers. 
It allows services to find and communicate with each other without hard coding hostname and port. The only ‘fixed point’ in such an architecture consists of a service registry with which each service has to register.
A drawback is that all clients must implement a certain logic to interact with this fixed point. This assumes an additional network round trip before the actual request.
In AWS cloud, because of its inherent nature, servers come and go. Unlike the traditional load balancers which work with servers with well known IP addresses and host names, in AWS, load balancing requires much more sophistication in registering and de-registering servers with load balancer on the fly.

The setups involve the following

- **Eureka Server**: A service registry is a phone book for your microservices. Each service registers itself with the service registry and tells the registry where it lives (host, port, node name) and perhaps other service-specific metadata - things that other services can use to make informed decisions about it. 

- **Eureka Client**:  A client retrieves a list of all connected peers of a service registry and makes all further requests to any other services through a load-balancing algorithm. Your architecture which is using Eureka will typically have two applications
	- **Application Client** which uses Eureka Client to make requests to the Application Service.
	- **Application Service** which receives requests from Application Client and sends a response back.
	
Configuration:
- **Eureka Server:**
1. Dependency - spring-cloud-starter-eureka-server

2. Add @EnableEurekaServer to @SpringBootApplication class.

3. Add following properties.
```
eureka.client.registerWithEureka=false
eureka.client.fetchRegistry=false
```
We are telling the built-in Eureka Client not to register with ‘itself’, because our application should be acting as a server.

4. start the server and check Eureka dashboard at default host:port like http://localhost:8761

**Eureka client- Application Service:**

1. Dependency - spring-cloud-starter-eureka

2. Add @EnableEurekaClient to @SpringBootApplication class.

3. Register service at Eureka server.
```
server.port=0
spring.application.name=spring-cloud-eureka-client
eureka.client.serviceUrl.defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
```
Note that all the instances/nodes of this application server should have same spring.application.name but different server.port.

4. Start Eureka server and this application service. Observe the serve getting registered with spring.application.name value.

**Eureka client- Application Client:**

